name: Run Python Script Daily at 2:30 AM

on:
  schedule:
    - cron: '30 4 * * *'  # Runs every day at 4:30 AM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install datetime requests==2.26.0 beautifulsoup4==4.10.0 cloudscraper selenium retrying

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@master

    - name: Run Bitcoin ETF Scraper
      run: python bitcoin_etf_scraper.py

    - name: Run BTC Flows Coinglass
      run: python btc_flows_coinglass.py

    - name: Limitless
      run: limitlesss.py  
